
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author T-Gamer
 */
public class acao extends javax.swing.JFrame {

    /**
     * Creates new form acao
     */
    public acao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        pnlTelaAcao = new javax.swing.JPanel();
        lblTelaAcao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCopra1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mnuTelaAcao = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlTelaAcao.setDoubleBuffered(false);
        pnlTelaAcao.setFocusCycleRoot(true);
        pnlTelaAcao.setLayout(null);

        lblTelaAcao.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblTelaAcao.setText("Livros book");
        pnlTelaAcao.add(lblTelaAcao);
        lblTelaAcao.setBounds(150, 10, 150, 40);

        getContentPane().add(pnlTelaAcao);
        pnlTelaAcao.setBounds(0, 0, 600, 60);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        btnCopra1.setText("Compra");
        btnCopra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopra1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCopra1);
        btnCopra1.setBounds(80, 30, 55, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Documents\\NetBeansProjects\\aula7padaria\\src\\imagens\\acao.jpg")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 130, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 90, 150, 80);

        mnuTelaAcao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuTelaAcao.setPreferredSize(new java.awt.Dimension(66, 40));

        jMenu2.setText("Ação");
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu2);

        jMenu5.setText("Aventura");
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu5);

        jMenu6.setText("Ficção");
        jMenu6.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu6);

        jMenu7.setText("Terro");
        jMenu7.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu7);

        jMenu3.setText("Romance");
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu3);

        jMenu4.setText("Drama");
        jMenu4.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaAcao.add(jMenu4);

        setJMenuBar(mnuTelaAcao);

        setSize(new java.awt.Dimension(612, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        
        teladoproduto car;
        car = new teladoproduto();
        car.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnCopra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopra1ActionPerformed
        telacompra pra;
        pra = new telacompra();
        pra.setVisible(true);
    }//GEN-LAST:event_btnCopra1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        teladoproduto car;
        car = new teladoproduto();
        car.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopra1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTelaAcao;
    private javax.swing.JMenuBar mnuTelaAcao;
    private javax.swing.JPanel pnlTelaAcao;
    // End of variables declaration//GEN-END:variables
}
