
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author T-Gamer
 */
public class telacompra extends javax.swing.JFrame {

    /**
     * Creates new form telacompra
     */
    public telacompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaCompra = new javax.swing.JPanel();
        lblTelaCompra = new javax.swing.JLabel();
        pnlVisaoTotal = new javax.swing.JPanel();
        lblImagemf = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlEndereço = new javax.swing.JPanel();
        lblRua = new javax.swing.JLabel();
        txtNomeDaRua = new javax.swing.JTextField();
        lblDigite = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        pnlFinalizar = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        btnFinalizaCompra = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        mnuTelaCompra = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlTelaCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTelaCompra.setDoubleBuffered(false);
        pnlTelaCompra.setFocusCycleRoot(true);
        pnlTelaCompra.setLayout(null);

        lblTelaCompra.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblTelaCompra.setText("Livros book");
        pnlTelaCompra.add(lblTelaCompra);
        lblTelaCompra.setBounds(220, 10, 150, 40);

        getContentPane().add(pnlTelaCompra);
        pnlTelaCompra.setBounds(0, 0, 600, 60);

        pnlVisaoTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlVisaoTotal.setLayout(null);

        lblImagemf.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Documents\\NetBeansProjects\\aula7padaria\\src\\imagens\\acao.jpg")); // NOI18N
        pnlVisaoTotal.add(lblImagemf);
        lblImagemf.setBounds(10, 10, 140, 80);

        lblTexto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto.setText("trigo do sul a nova onda do pao ");
        pnlVisaoTotal.add(lblTexto);
        lblTexto.setBounds(160, 10, 190, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("R$ 49,90");
        pnlVisaoTotal.add(jLabel1);
        jLabel1.setBounds(160, 60, 100, 30);

        getContentPane().add(pnlVisaoTotal);
        pnlVisaoTotal.setBounds(0, 60, 600, 100);

        pnlEndereço.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlEndereço.setLayout(null);

        lblRua.setText("rua ");
        pnlEndereço.add(lblRua);
        lblRua.setBounds(10, 40, 41, 16);

        txtNomeDaRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDaRuaActionPerformed(evt);
            }
        });
        pnlEndereço.add(txtNomeDaRua);
        txtNomeDaRua.setBounds(10, 60, 180, 24);

        lblDigite.setText("Digite Seu Endereço");
        pnlEndereço.add(lblDigite);
        lblDigite.setBounds(210, 10, 130, 16);

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        pnlEndereço.add(txtNumero);
        txtNumero.setBounds(260, 60, 60, 24);

        lblNumero.setText("Numero");
        pnlEndereço.add(lblNumero);
        lblNumero.setBounds(260, 40, 60, 16);

        lblCep.setText("CEP");
        pnlEndereço.add(lblCep);
        lblCep.setBounds(420, 40, 25, 16);
        pnlEndereço.add(txtCep);
        txtCep.setBounds(400, 60, 180, 24);

        getContentPane().add(pnlEndereço);
        pnlEndereço.setBounds(0, 160, 600, 90);

        pnlFinalizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlFinalizar.setLayout(null);

        jRadioButton1.setText("  Boleto");
        pnlFinalizar.add(jRadioButton1);
        jRadioButton1.setBounds(50, 70, 140, 28);

        btnFinalizaCompra.setText("Finalizar Compra");
        btnFinalizaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaCompraActionPerformed(evt);
            }
        });
        pnlFinalizar.add(btnFinalizaCompra);
        btnFinalizaCompra.setBounds(420, 80, 170, 24);

        jRadioButton2.setText("   Cartao de Credito");
        pnlFinalizar.add(jRadioButton2);
        jRadioButton2.setBounds(50, 20, 150, 28);

        getContentPane().add(pnlFinalizar);
        pnlFinalizar.setBounds(0, 250, 600, 130);

        mnuTelaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuTelaCompra.setPreferredSize(new java.awt.Dimension(66, 40));

        jMenu2.setText("Ação");
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 21));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        mnuTelaCompra.add(jMenu2);

        jMenu5.setText("Aventura");
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaCompra.add(jMenu5);

        jMenu6.setText("Ficção");
        jMenu6.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaCompra.add(jMenu6);

        jMenu7.setText("Terro");
        jMenu7.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaCompra.add(jMenu7);

        jMenu3.setText("Romance");
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaCompra.add(jMenu3);

        jMenu4.setText("Drama");
        jMenu4.setPreferredSize(new java.awt.Dimension(40, 21));
        mnuTelaCompra.add(jMenu4);

        setJMenuBar(mnuTelaCompra);

        setSize(new java.awt.Dimension(612, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        acao ac;
        ac = new acao();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txtNomeDaRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDaRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDaRuaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnFinalizaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaCompraActionPerformed
       JOptionPane.showMessageDialog(null,"Pedido Finalizado " );
       
    }//GEN-LAST:event_btnFinalizaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telacompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telacompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telacompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telacompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telacompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizaCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblDigite;
    private javax.swing.JLabel lblImagemf;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelaCompra;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JMenuBar mnuTelaCompra;
    private javax.swing.JPanel pnlEndereço;
    private javax.swing.JPanel pnlFinalizar;
    private javax.swing.JPanel pnlTelaCompra;
    private javax.swing.JPanel pnlVisaoTotal;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtNomeDaRua;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
