
public class teladoproduto extends javax.swing.JFrame {


    public teladoproduto() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaProduto = new javax.swing.JPanel();
        lblTelaProduto = new javax.swing.JLabel();
        pnlimagem = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lblNomeTrigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCompra = new javax.swing.JButton();
        mnuTelaProduto = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlTelaProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTelaProduto.setDoubleBuffered(false);
        pnlTelaProduto.setFocusCycleRoot(true);
        pnlTelaProduto.setLayout(null);

        lblTelaProduto.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblTelaProduto.setText("Livros book");
        pnlTelaProduto.add(lblTelaProduto);
        lblTelaProduto.setBounds(220, 10, 150, 40);

        getContentPane().add(pnlTelaProduto);
        pnlTelaProduto.setBounds(0, 0, 600, 60);

        pnlimagem.setLayout(null);

        lblImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\T-Gamer\\Documents\\NetBeansProjects\\aula7padaria\\src\\imagens\\acao.jpg")); // NOI18N
        pnlimagem.add(lblImagem);
        lblImagem.setBounds(20, 30, 130, 200);

        getContentPane().add(pnlimagem);
        pnlimagem.setBounds(60, 70, 180, 240);

        jScrollPane1.setBorder(null);

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPane1.setText("Bryce Quinlan e Hunt Athalar fizeram um pacto. Enquanto processam os eventos da última primavera, eles irão manter as coisas… platônicas… até o solstício. Eles salvaram a Cidade da Lua Crescente, mas com tanto frenesi acontecendo ultimamente, eles desejam, mais do que qualquer coisa, uma oportunidade de relaxar. Desacelerar. E descobrir o que o futuro lhes reserva. Mas quando a tensão suspensa entre os dois alcançar um nível insustentável, prestes a incendiar a Cidade da Lua Crescente, eles serão capazes de resistir?");
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 190, 280, 100);

        lblNomeTrigo.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        lblNomeTrigo.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeTrigo.setText("trigo do sul a nova onda do pao ");
        getContentPane().add(lblNomeTrigo);
        lblNomeTrigo.setBounds(300, 80, 280, 50);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("R$ 49,90");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 130, 80, 40);

        btnCompra.setText("Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompra);
        btnCompra.setBounds(370, 320, 80, 30);

        mnuTelaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnuTelaProduto.setPreferredSize(new java.awt.Dimension(66, 40));

        jMenu2.setText("Ação");
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 21));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        mnuTelaProduto.add(jMenu2);

        jMenu5.setText("Aventura");
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaProduto.add(jMenu5);

        jMenu6.setText("Ficção");
        jMenu6.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaProduto.add(jMenu6);

        jMenu7.setText("Terro");
        jMenu7.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaProduto.add(jMenu7);

        jMenu3.setText("Romance");
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 21));
        mnuTelaProduto.add(jMenu3);

        jMenu4.setText("Drama");
        jMenu4.setPreferredSize(new java.awt.Dimension(40, 21));
        mnuTelaProduto.add(jMenu4);

        setJMenuBar(mnuTelaProduto);

        setSize(new java.awt.Dimension(612, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        acao ac;
        ac = new acao();
        ac.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        telacompra pra;
        pra = new telacompra();
        pra.setVisible(true);
      
    }//GEN-LAST:event_btnCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teladoproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teladoproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teladoproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teladoproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teladoproduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNomeTrigo;
    private javax.swing.JLabel lblTelaProduto;
    private javax.swing.JMenuBar mnuTelaProduto;
    private javax.swing.JPanel pnlTelaProduto;
    private javax.swing.JPanel pnlimagem;
    // End of variables declaration//GEN-END:variables
}
