
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Telatabela extends javax.swing.JFrame {

    DefaultTableModel model;

    public Telatabela() {
        initComponents();

        model = (DefaultTableModel) tblTabela.getModel();

        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnVoltar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnConsultar.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtBookPreco.setEnabled(true);
        
         txtEscolha.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSecundaria = new javax.swing.JPanel();
        lblCadastro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        pnlBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        pnlEscreva = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEscritor = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtEscritor = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        pnlBusca = new javax.swing.JPanel();
        cmbVarios = new javax.swing.JComboBox<>();
        txtEscolha = new javax.swing.JTextField();
        lblProcura = new javax.swing.JLabel();
        lblOpcao = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblBusqueProcura = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbBook = new javax.swing.JLabel();
        txtBookPreco = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Tabela");
        getContentPane().setLayout(null);

        pnlSecundaria.setBackground(new java.awt.Color(0, 0, 255));

        lblCadastro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastro.setText("Cadastro ");

        tblTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblTabela.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Escritor", "Editora", "Genero", "Ano", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTabela.setGridColor(new java.awt.Color(0, 0, 0));
        tblTabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTabela.setShowGrid(false);
        tblTabela.setShowHorizontalLines(true);
        tblTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTabelaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabela);

        pnlBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBotoes.setForeground(new java.awt.Color(204, 204, 204));

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlEscreva.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitulo.setText("Titulo");

        lblEscritor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEscritor.setText("Escritor");

        lblEditora.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEditora.setText("Editora");

        lblAno.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblAno.setText("Ano de lancamento");

        lblQuantidade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblQuantidade.setText("Quantidade");

        lblGenero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGenero.setText("Genero");

        lblPreco.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPreco.setText("Preço");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEscrevaLayout = new javax.swing.GroupLayout(pnlEscreva);
        pnlEscreva.setLayout(pnlEscrevaLayout);
        pnlEscrevaLayout.setHorizontalGroup(
            pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscrevaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEscrevaLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEscrevaLayout.createSequentialGroup()
                        .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEscritor, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(255, 255, 255))
                    .addGroup(pnlEscrevaLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEscritor, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                    .addGroup(pnlEscrevaLayout.createSequentialGroup()
                        .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtQuantidade))
                            .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlEscrevaLayout.setVerticalGroup(
            pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscrevaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscritor)
                    .addComponent(txtEscritor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditora)
                    .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscrevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pnlBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbVarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Titulo", "Escritor", "Editora", "Genero", "Ano de lançamento", "Quantidade" }));
        cmbVarios.setPreferredSize(new java.awt.Dimension(130, 26));
        cmbVarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVariosItemStateChanged(evt);
            }
        });

        lblProcura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblProcura.setText("Escreva o que procura");

        lblOpcao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblOpcao.setText("Escolha uma opção");

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblBusqueProcura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBusqueProcura.setText("Busque o que procura");

        javax.swing.GroupLayout pnlBuscaLayout = new javax.swing.GroupLayout(pnlBusca);
        pnlBusca.setLayout(pnlBuscaLayout);
        pnlBuscaLayout.setHorizontalGroup(
            pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbVarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEscolha)
                    .addComponent(lblProcura, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBuscaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblBusqueProcura, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBuscaLayout.setVerticalGroup(
            pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcura)
                    .addComponent(lblOpcao)
                    .addComponent(lblBusqueProcura, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(7, 7, 7))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtBookPreco.setText("R$ ");
        txtBookPreco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtBookPreco.setEnabled(false);
        txtBookPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSecundariaLayout = new javax.swing.GroupLayout(pnlSecundaria);
        pnlSecundaria.setLayout(pnlSecundariaLayout);
        pnlSecundariaLayout.setHorizontalGroup(
            pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecundariaLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblCadastro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSecundariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlSecundariaLayout.createSequentialGroup()
                            .addComponent(pnlEscreva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnlBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSecundariaLayout.setVerticalGroup(
            pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSecundariaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSecundariaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBookPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSecundariaLayout.createSequentialGroup()
                        .addGroup(pnlSecundariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEscreva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addGap(156, 156, 156))
        );

        getContentPane().add(pnlSecundaria);
        pnlSecundaria.setBounds(25, 30, 840, 560);
        pnlSecundaria.getAccessibleContext().setAccessibleName("");

        getContentPane().add(lblCor);
        lblCor.setBounds(1, 0, 890, 590);

        setSize(new java.awt.Dimension(911, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

  if (txtTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Titulo esta vazio");
            txtTitulo.requestFocus();
            return;
        } else if (txtEscritor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Escritor esta vazio");
            txtEscritor.requestFocus();
            return;
        } else if (txtEditora.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Editora esta vazio");
            txtEditora.requestFocus();
            return;
        } else if (txtGenero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Genero esta vazio");
            txtGenero.requestFocus();
            return;
        }else if (txtAno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Ano esta vazio");
            txtAno.requestFocus();
            return;
        }else if (txtQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "o campo Quantidade esta vazio");
            txtQuantidade.requestFocus();
            return;
        }



        try {
            Connection con;
            PreparedStatement ps;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);

            ps = con.prepareStatement("INSERT INTO livros VALUES(?,?,?,?,?,?)");
            ps.setString(1, txtTitulo.getText());
            ps.setString(2, txtEscritor.getText());
            ps.setString(3, txtEditora.getText());
             ps.setString(4, txtGenero.getText());
            ps.setInt(5, Integer.parseInt(txtAno.getText()));
            ps.setInt(6, Integer.parseInt(txtQuantidade.getText()));
           
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "dados salvos com sucesso");
            txtTitulo.setText("");
            txtEscritor.setText("");
            txtEditora.setText("");
            txtAno.setText("");
            txtQuantidade.setText("");
            txtGenero.setText("");
            txtPreco.setText("");
            txtTitulo.requestFocus();

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro " + ex.getMessage() + "\nEntre em contato com o administrador e informe");
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(null, "O Nome que você usou ja esta cadastrador tente outro");
                txtTitulo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "error numero" + ex.getErrorCode() + "\nEntre em contato com o administrador e informe o número do erro");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            Connection conexao;
            PreparedStatement st;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);
            st = conexao.prepareStatement("UPDATE livros SET escritor = ?, editora = ?, genero = ?, ano = ?, quantidade = ?, preco = ? WHERE titulo = ?");
            st.setString(1, txtEscritor.getText());
            st.setString(2, txtEditora.getText());
            st.setString(3, txtGenero.getText());
            st.setString(4, txtAno.getText());
            st.setString(5, txtQuantidade.getText());
            st.setString(6, txtPreco.getText());
            st.setString(7, txtTitulo.getText());

            st.executeUpdate();

            JOptionPane.showMessageDialog(null, "Alteração realizada com sucesso");
            txtTitulo.setText("");
            txtEscritor.setText("");
            txtEditora.setText("");
            txtAno.setText("");
            txtQuantidade.setText("");
            txtGenero.setText("");
            txtBookPreco.setText("R$ " + txtPreco.getText());
            txtPreco.setText("");
            txtTitulo.requestFocus();

            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnVoltar.setEnabled(false);
            txtPreco.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnConsultar.setEnabled(true);
            txtTitulo.setEnabled(true);
          

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto" + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        if (txtTitulo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o Titulo do Livro");
            txtTitulo.requestFocus();
            return;
        }
        
        
        try {
            Connection co; 
            PreparedStatement sta; 
            ResultSet reu;   
            Class.forName("com.mysql.cj.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);

            sta = co.prepareStatement("SELECT * FROM  livros WHERE  titulo LIKE ?");
            sta.setString(1, "%" + txtTitulo.getText() + "%" );
            reu = sta.executeQuery();
            if (reu.next()) {
                txtTitulo.setText(reu.getString("titulo"));
                txtEscritor.setText(reu.getString("escritor"));
                txtEditora.setText(reu.getString("editora"));
                txtGenero.setText(reu.getString("genero"));
                txtAno.setText(reu.getString("ano"));
                txtQuantidade.setText(reu.getString("quantidade"));
                txtPreco.setText(reu.getFloat("preco")+"");
                txtBookPreco.setText("R$ " + reu.getFloat("preco"));
                lbBook.setIcon(new javax.swing.ImageIcon(".\\src\\imagens\\"+reu.getString("titulo")+".jpg"));
                

                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnVoltar.setEnabled(true);
                btnSalvar.setEnabled(false);
                btnConsultar.setEnabled(false);
                txtTitulo.setEnabled(false);
                txtPreco.setEnabled(true);
            //    model.setRowCount(0);
                txtTitulo.requestFocus();

            }else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
                txtTitulo.requestFocus();
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            int resultado;       
            Connection co;
            PreparedStatement sta;
            Class.forName("com.mysql.cj.jdbc.Driver");
            co = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);
            sta = co.prepareStatement("DELETE FROM livros WHERE titulo=?");
            sta.setString(1, txtTitulo.getText());
            resultado = sta.executeUpdate();

            if (resultado == 1) { 
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso");
                txtTitulo.setText("");
                txtEscritor.setText("");
                txtEditora.setText("");
                 txtGenero.setText("");
                txtAno.setText("");
                txtQuantidade.setText("");
                txtPreco.setText("");
                txtTitulo.requestFocus();

                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnVoltar.setEnabled(false);
                btnSalvar.setEnabled(true);
                btnConsultar.setEnabled(true);
                txtTitulo.setEnabled(true);
                txtPreco.setEnabled(true);

            } else { 
                JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto com este código");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String varios;
        varios = cmbVarios.getSelectedItem().toString();

        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;

            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);

            if (varios.equalsIgnoreCase("Geral")) {
                st = conexao.prepareStatement("SELECT * From livros");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                    Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }

            } else if (varios.equalsIgnoreCase("Titulo")) {

                st = conexao.prepareStatement("SELECT * FROM livros WHERE titulo LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                    Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }
            } else if (varios.equalsIgnoreCase("Escritor")) {

                st = conexao.prepareStatement("SELECT * From livros WHERE escritor LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                     Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }

            } else if (varios.equalsIgnoreCase("Editora")) {

                st = conexao.prepareStatement("SELECT * From livros WHERE editora LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                     Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }

            } else if (varios.equalsIgnoreCase("Genero")) {

                st = conexao.prepareStatement("SELECT * From livros WHERE genero LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                    Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }
            }else if (varios.equalsIgnoreCase("Ano de lançamento")) {

                st = conexao.prepareStatement("SELECT * From livros WHERE ano LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                     Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }

            } else if (varios.equalsIgnoreCase("Quantidade")) {

                st = conexao.prepareStatement("SELECT * From livros WHERE quantidade LIKE ?");
                st.setString(1, "%" + txtEscolha.getText() + "%");
                resultado = st.executeQuery();

                txtEscolha.setText("");
                model.setRowCount(0);

                while (resultado.next()) { 
                     Object[] linha = {resultado.getString("titulo"), resultado.getString("escritor"), resultado.getString("editora"), resultado.getString("genero"), resultado.getString("ano"), resultado.getString("quantidade")};
                    model.addRow(linha);

                }
            } 

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbVariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVariosItemStateChanged
        String tipo;
        tipo = cmbVarios.getSelectedItem().toString();
        if (tipo.equalsIgnoreCase("Escritor")) {

            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        } else if (tipo.equalsIgnoreCase("Titulo")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        } else if (tipo.equalsIgnoreCase("Editora")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        }else if (tipo.equalsIgnoreCase("Genero")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        }else if (tipo.equalsIgnoreCase("Ano de lançamento")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        } else if (tipo.equalsIgnoreCase("Quantidade")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(true);
            model.setRowCount(0);

        }  else if (tipo.equalsIgnoreCase("Geral")) {
            txtEscolha.setText("");
            txtEscolha.setEnabled(false);
            model.setRowCount(0);

        }


    }//GEN-LAST:event_cmbVariosItemStateChanged

    private void txtBookPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookPrecoActionPerformed

    private void tblTabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabelaMouseReleased
        String title = tblTabela.getValueAt(tblTabela.getSelectedRow(), 0).toString();
        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);
            ps = con.prepareStatement("SELECT titulo, preco FROM livros where titulo=?");
            ps.setString(1, title);
            rs = ps.executeQuery();
            rs.next();
            lbBook.setIcon(new javax.swing.ImageIcon(".\\src\\imagens\\"+rs.getString(1)+".jpg"));
            txtBookPreco.setText("R$ " + rs.getString(2));
            txtTitulo.setText(rs.getString(1));
            txtTitulo.requestFocus();
            txtTitulo.selectAll();
        } catch ( ClassNotFoundException | SQLException e){
        }
    }//GEN-LAST:event_tblTabelaMouseReleased

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        txtEscritor.setText("");
        txtEditora.setText("");
        txtAno.setText("");
        txtQuantidade.setText("");
        txtGenero.setText("");
        txtPreco.setText("");
        txtTitulo.requestFocus();

        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnVoltar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnConsultar.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtPreco.setEnabled(true);
    }                                         

    private void tblTabelaMouseClicked(java.awt.event.MouseEvent evt) {
        String title = tblTabela.getValueAt(tblTabela.getSelectedRow(), 0).toString();
        try {
            Connection con;
            PreparedStatement ps;
            ResultSet rs;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookpay", "root", TelaUsuario.dbPassword);
            ps = con.prepareStatement("SELECT titulo, preco FROM livros where titulo=?");
            ps.setString(1, title);
            rs = ps.executeQuery();
            rs.next();
            lbBook.setIcon(new javax.swing.ImageIcon(".\\src\\imagens\\"+rs.getString(1)+".jpg"));
            txtBookPreco.setText("R$ " + rs.getString(2));
            txtTitulo.setText(rs.getString(1));
            txtTitulo.requestFocus();
            txtTitulo.selectAll();
        } catch ( ClassNotFoundException | SQLException e){
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telatabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telatabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbVarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBook;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblBusqueProcura;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblEscritor;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblOpcao;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProcura;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlBusca;
    private javax.swing.JPanel pnlEscreva;
    private javax.swing.JPanel pnlSecundaria;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBookPreco;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtEscolha;
    private javax.swing.JTextField txtEscritor;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
